apiVersion: v1
baseDomain: dpl.local
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata: 
  name: ocp4
networking:
  networkType: ncp
  clusterNetwork:
  - cidr: 10.100.0.0/16
    hostPrefix: 23
  machineCIDR: 172.27.0.0/24
  serviceNetwork:
  - 10.200.0.0/16
platform:
  vsphere:
    vcenter: vcenter-vsan.vrack.vsphere.local
    username: Administrator@vsphere.local
    password: xxx
    datacenter: vi-cluster
    defaultDatastore: cls2-vSanDatastore
    fips: false
pullSecret: 'xxx'
sshKey: 'xxx'
